name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: check golang version
      run: go version

    - name: create env
      run: cp .env.example .env

    - name: build project
      run: make build
